trigger:
- main

variables:
  buildConfiguration: 'Release'
  webRepository: 'web'
  tag: '$(Build.BuildId)'

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
- task: GoTool@0
  inputs:
    version: '1.17'
- task: Go@0
  inputs:
    command: 'get'
    arguments: 'github.com/go-sql-driver/mysql'
- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'

- task: Docker@2
  displayName: 'Build and push the image to container registry'
  inputs:
    command: buildAndPush
    buildContext: $(Build.Repository.LocalPath)
    repository: $(webRepository)
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    containerRegistry: 'Container Registry Connection'
    tags: |
      $(tag)

- task: AzureWebAppContainer@1
  inputs:
   appName: $(WebAppName)
   azureSubscription: 'Resource Manager - wiki'
   imageName: $(RegistryName)/$(webRepository):$(build.buildId)